Φόρτωση dataset με βάση το documentation

In [1]:
import pickle

filepath = "cifar-10-batches-py"
def load_cifar_batch(filepath):
    with open(filepath, 'rb') as f:
        batch = pickle.load(f, encoding='bytes')
    return batch


Φόρτωση κάθε ενός batch αρχείου από τον φάκελο και χωρίζω σε train, test

Χρήση array της numpy

In [2]:
import numpy as np

X_train_list = []
y_train_list = []

for i in range(1, 6):
    batch = load_cifar_batch(f"cifar-10-batches-py/data_batch_{i}")
    X_train_list.append(batch[b'data'])
    y_train_list.extend(batch[b'labels'])

#ενοποίηση arrays κάθετα
X_train = np.vstack(X_train_list)
y_train = np.array(y_train_list)


In [3]:
meta = load_cifar_batch("cifar-10-batches-py/batches.meta")
label_names = meta[b'label_names']
print(label_names)


[b'airplane', b'automobile', b'bird', b'cat', b'deer', b'dog', b'frog', b'horse', b'ship', b'truck']


Φόρτωση και δημιουργία test data

In [4]:
test_batch = load_cifar_batch("cifar-10-batches-py/test_batch")

X_test = test_batch[b'data']
y_test = test_batch[b'labels']

In [5]:
print(X_test)

[[158 159 165 ... 124 129 110]
 [235 231 232 ... 178 191 199]
 [158 158 139 ...   8   3   7]
 ...
 [ 20  19  15 ...  50  53  47]
 [ 25  15  23 ...  80  81  80]
 [ 73  98  99 ...  94  58  26]]


In [6]:
print(y_test[:50])

[3, 8, 8, 0, 6, 6, 1, 6, 3, 1, 0, 9, 5, 7, 9, 8, 5, 7, 8, 6, 7, 0, 4, 9, 5, 2, 4, 0, 9, 6, 6, 5, 4, 5, 9, 2, 4, 1, 9, 5, 4, 6, 5, 6, 0, 9, 3, 9, 7, 6]


Επιλογή υπό-κλάσεων

In [7]:
selected_classes = [2,3,5]
classes_names = ['bird', 'cat', 'dog']

y_test = np.array(y_test)


mask_train = np.isin(y_train, selected_classes)
X_train_sub = X_train[mask_train]
y_train_sub = y_train[mask_train]

mask_test = np.isin(y_test, selected_classes)
X_test_sub = X_test[mask_test]
y_test_sub = y_test[mask_test]

In [8]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

Εφαρμογή Scaling στα δεδομένα για πιο αξιόλογα αποτελέσματα.

In [9]:
scaler = StandardScaler()

scaler.fit(X_train_sub)

X_test_scaled = scaler.transform(X_test_sub)
X_train_scaled = scaler.transform(X_train_sub)

Εφαρμογή PCA.

Μείωση των components σε 150.

In [10]:
pca = PCA(n_components= 150)

pca.fit(X_train_scaled)

X_test = pca.transform(X_test_scaled)
X_train = pca.transform(X_train_scaled)

/Users/dimkostir/Desktop/ΜΕΤΑΠΤΥΧΙΑΚΟ/ΜΕΤΑΠΤΥΧΙΑΚΟ/ΜΗΧΑΝΙΚΗ ΜΑΘΗΣΗ/Τελέλης ΕΡΓΑΣΙΑ/venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:335: RuntimeWarning: divide by zero encountered in matmul
  Q, _ = normalizer(A @ Q)
/Users/dimkostir/Desktop/ΜΕΤΑΠΤΥΧΙΑΚΟ/ΜΕΤΑΠΤΥΧΙΑΚΟ/ΜΗΧΑΝΙΚΗ ΜΑΘΗΣΗ/Τελέλης ΕΡΓΑΣΙΑ/venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:335: RuntimeWarning: overflow encountered in matmul
  Q, _ = normalizer(A @ Q)
/Users/dimkostir/Desktop/ΜΕΤΑΠΤΥΧΙΑΚΟ/ΜΕΤΑΠΤΥΧΙΑΚΟ/ΜΗΧΑΝΙΚΗ ΜΑΘΗΣΗ/Τελέλης ΕΡΓΑΣΙΑ/venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:335: RuntimeWarning: invalid value encountered in matmul
  Q, _ = normalizer(A @ Q)
/Users/dimkostir/Desktop/ΜΕΤΑΠΤΥΧΙΑΚΟ/ΜΕΤΑΠΤΥΧΙΑΚΟ/ΜΗΧΑΝΙΚΗ ΜΑΘΗΣΗ/Τελέλης ΕΡΓΑΣΙΑ/venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:336: RuntimeWarning: divide by zero encountered in matmul
  Q, _ = normalizer(A.T @ Q)
/Users/dimkostir/Desktop/ΜΕΤΑΠΤΥΧΙΑΚΟ/ΜΕΤΑΠΤΥΧΙΑΚΟ/ΜΗΧΑΝΙΚΗ ΜΑΘΗΣΗ/Τελέλης ΕΡΓΑΣΙΑ/venv/lib/pyth

Βλέπουμε όντως ότι τα features μειώθηκαν σε 150.

In [11]:
print(X_train.shape)

(15000, 150)


Μοντέλο 1: Logistic Regression

In [12]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression(max_iter= 2000)

log_reg.fit(X_train, y_train_sub)

/Users/dimkostir/Desktop/ΜΕΤΑΠΤΥΧΙΑΚΟ/ΜΕΤΑΠΤΥΧΙΑΚΟ/ΜΗΧΑΝΙΚΗ ΜΑΘΗΣΗ/Τελέλης ΕΡΓΑΣΙΑ/venv/lib/python3.9/site-packages/sklearn/linear_model/_linear_loss.py:203: RuntimeWarning: divide by zero encountered in matmul
  raw_prediction = X @ weights.T + intercept  # ndarray, likely C-contiguous
/Users/dimkostir/Desktop/ΜΕΤΑΠΤΥΧΙΑΚΟ/ΜΕΤΑΠΤΥΧΙΑΚΟ/ΜΗΧΑΝΙΚΗ ΜΑΘΗΣΗ/Τελέλης ΕΡΓΑΣΙΑ/venv/lib/python3.9/site-packages/sklearn/linear_model/_linear_loss.py:203: RuntimeWarning: overflow encountered in matmul
  raw_prediction = X @ weights.T + intercept  # ndarray, likely C-contiguous
/Users/dimkostir/Desktop/ΜΕΤΑΠΤΥΧΙΑΚΟ/ΜΕΤΑΠΤΥΧΙΑΚΟ/ΜΗΧΑΝΙΚΗ ΜΑΘΗΣΗ/Τελέλης ΕΡΓΑΣΙΑ/venv/lib/python3.9/site-packages/sklearn/linear_model/_linear_loss.py:203: RuntimeWarning: invalid value encountered in matmul
  raw_prediction = X @ weights.T + intercept  # ndarray, likely C-contiguous
/Users/dimkostir/Desktop/ΜΕΤΑΠΤΥΧΙΑΚΟ/ΜΕΤΑΠΤΥΧΙΑΚΟ/ΜΗΧΑΝΙΚΗ ΜΑΘΗΣΗ/Τελέλης ΕΡΓΑΣΙΑ/venv/lib/python3.9/site-packages/sklearn/linear_model/_l

LogisticRegression(max_iter=2000)

In [13]:
log_reg_pred = log_reg.predict(X_test)

/Users/dimkostir/Desktop/ΜΕΤΑΠΤΥΧΙΑΚΟ/ΜΕΤΑΠΤΥΧΙΑΚΟ/ΜΗΧΑΝΙΚΗ ΜΑΘΗΣΗ/Τελέλης ΕΡΓΑΣΙΑ/venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/dimkostir/Desktop/ΜΕΤΑΠΤΥΧΙΑΚΟ/ΜΕΤΑΠΤΥΧΙΑΚΟ/ΜΗΧΑΝΙΚΗ ΜΑΘΗΣΗ/Τελέλης ΕΡΓΑΣΙΑ/venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/dimkostir/Desktop/ΜΕΤΑΠΤΥΧΙΑΚΟ/ΜΕΤΑΠΤΥΧΙΑΚΟ/ΜΗΧΑΝΙΚΗ ΜΑΘΗΣΗ/Τελέλης ΕΡΓΑΣΙΑ/venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b


In [14]:
from sklearn.metrics import confusion_matrix, classification_report

log_reg_cl_rep = classification_report(y_test_sub, log_reg_pred, digits= 4)
print("\nClassification Report LR:\n",log_reg_cl_rep)


Classification Report LR:
               precision    recall  f1-score   support

           2     0.5842    0.6380    0.6099      1000
           3     0.5080    0.5070    0.5075      1000
           5     0.5209    0.4740    0.4963      1000

    accuracy                         0.5397      3000
   macro avg     0.5377    0.5397    0.5379      3000
weighted avg     0.5377    0.5397    0.5379      3000



In [15]:
log_reg_conf_matrix = confusion_matrix(y_test_sub, log_reg_pred)
print("\nConfusion Matrix LR\n\n",log_reg_conf_matrix)


Confusion Matrix LR

 [[638 204 158]
 [215 507 278]
 [239 287 474]]


In [16]:
test_accLR = log_reg.score(X_test, y_test_sub)
train_accLR = log_reg.score(X_train, y_train_sub)

print("\nTrain accuracy LR:", train_accLR)
print("\nTest accuracy LR:", test_accLR)


Train accuracy LR: 0.5498

Test accuracy LR: 0.5396666666666666


/Users/dimkostir/Desktop/ΜΕΤΑΠΤΥΧΙΑΚΟ/ΜΕΤΑΠΤΥΧΙΑΚΟ/ΜΗΧΑΝΙΚΗ ΜΑΘΗΣΗ/Τελέλης ΕΡΓΑΣΙΑ/venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/dimkostir/Desktop/ΜΕΤΑΠΤΥΧΙΑΚΟ/ΜΕΤΑΠΤΥΧΙΑΚΟ/ΜΗΧΑΝΙΚΗ ΜΑΘΗΣΗ/Τελέλης ΕΡΓΑΣΙΑ/venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/dimkostir/Desktop/ΜΕΤΑΠΤΥΧΙΑΚΟ/ΜΕΤΑΠΤΥΧΙΑΚΟ/ΜΗΧΑΝΙΚΗ ΜΑΘΗΣΗ/Τελέλης ΕΡΓΑΣΙΑ/venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/Users/dimkostir/Desktop/ΜΕΤΑΠΤΥΧΙΑΚΟ/ΜΕΤΑΠΤΥΧΙΑΚΟ/ΜΗΧΑΝΙΚΗ ΜΑΘΗΣΗ/Τελέλης ΕΡΓΑΣΙΑ/venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/dimkostir/Desktop/ΜΕΤΑΠΤΥΧΙΑΚΟ/ΜΕΤΑΠΤΥΧΙΑΚΟ/ΜΗΧΑΝΙΚΗ ΜΑΘΗΣΗ/Τελέλης ΕΡΓΑΣΙΑ/venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: Runt

Μοντέλο 2: KNN as classifier

In [17]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors= 10)

In [18]:
knn.fit(X_train, y_train_sub)

KNeighborsClassifier(n_neighbors=10)

In [19]:
knn_pred = knn.predict(X_test)

In [20]:
test_accKNN = knn.score(X_test, y_test_sub)
train_accKNN = knn.score(X_train, y_train_sub)

print("\nTrain accuracy KNN:", train_accKNN)
print("\nTest accuracy KNN:", test_accKNN)


Train accuracy KNN: 0.5754666666666667

Test accuracy KNN: 0.5096666666666667


In [21]:
knn_cl_rep = classification_report(y_test_sub, knn_pred, digits= 4)
print("\nClassification Report KNN:\n",knn_cl_rep)


Classification Report KNN:
               precision    recall  f1-score   support

           2     0.4670    0.8710    0.6080      1000
           3     0.5440    0.3340    0.4139      1000
           5     0.6219    0.3240    0.4260      1000

    accuracy                         0.5097      3000
   macro avg     0.5443    0.5097    0.4826      3000
weighted avg     0.5443    0.5097    0.4826      3000



In [22]:
print("\nConfusion Matrix KNN:\n\n", confusion_matrix(y_test_sub, knn_pred))


Confusion Matrix KNN:

 [[871  74  55]
 [524 334 142]
 [470 206 324]]
